added configuration class
alexshapalov/rubyai pull request #19
Opened 2024-02-27 23:28 UTC by sanyakosivchuk

do we need to extract something else from client class?

2024-03-01 21:01 UTC, alexshapalov commented
```
class Configuration
  # attr_reader :api_key

  attr_accessor :model, :messages, :temperature, :api_version, :api_key

  BASE_URL = "https://api.openai.com/v1/chat/completions"

  DEFAULT_API_VERSION = "v1"

  MODELS = {
    "gpt-4" => "gpt-4",
    "gpt-4-0314" => "gpt-4-0314",
    "gpt-4-32k" => "gpt-4-32k",
    "gpt-3.5-turbo" => "gpt-3.5-turbo",
    "gpt-3.5-turbo-0301" => "gpt-3.5-turbo-0301",
    "text-davinci-003" => "text-davinci-003"
  }

  DEFAULT_MODEL = "gpt-3.5-turbo"

  def initialize(api_key, model = DEFAULT_MODEL)
    @api_key = nil
    @model = model
    @api_version = DEFAULT_API_VERSION
  end
end

conf = Configuration.new("api_key")

p conf.model
```



```
require_relative "configuration"

# conf = Configuration.new("api_key")

# p conf.model

module RubyAI
  # class << self
  #   attr_writer :configuration
  # end

  def self.configuration
    @configuration ||= Configuration.new("api_key")
  end

  def self.call
    @configuration
  end

  def self.configure
    yield(configuration)
  end
end


p RubyAI.configuration

# Configure RubyAI

# p RubyAI::Configuration.new("api_key")

RubyAI.configure do |config|
  p config.api_key = 'new value for api_key 1'
  p config.model = 'new value for model 2'
end
```

2024-03-02 13:30 UTC, sanyakosivchuk commented
both me and @bodyyyya worked on Extract configuration class commit

2024-03-02 13:36 UTC, sanyakosivchuk commented
for now it works with
```
configuration = RubyAI::Configuration.new("YOUR_API_KEY", "Who is the best chess player in history?")
client = RubyAI::Client.new(configuration)
result = client.call
puts result.dig("choices", 0, "message", "content")
```
and
```
api_key = "YOUR_API_KEY"
messages = "Who is the best chess player in history?"
result = RubyAI::Client.new(api_key, messages).call
puts result.dig("choices", 0, "message", "content")
```
ill update readme later

2024-03-09 05:04 UTC, alexshapalov requested changes

2024-03-09 05:04 UTC, alexshapalov commented on lib/rubyai/client.rb
> +require 'faraday'
Do we need to require it here? json and faraday

2024-03-09 05:06 UTC, alexshapalov commented on lib/rubyai/client.rb
> +        req.headers.merge!(RubyAI::HTTP.build_headers(@configuration.api_key))
if we have **attr_reader :configuration** we can use everywhere just **configuration**

2024-03-09 05:08 UTC, alexshapalov requested changes

2024-03-09 05:08 UTC, alexshapalov commented on lib/rubyai/client.rb
> +    def apply_options(options)
Where do we use this method?

2024-03-09 05:08 UTC, alexshapalov commented on lib/rubyai/http.rb
> +    module_function
Do not use module_function; it is better to use **extend self**

2024-03-10 02:36 UTC, alexshapalov approved these changes

2024-03-10 02:36 UTC, merged